services:
  freeswitch:
    image: ghcr.io/mohan-cao/freeswitch-docker-image:nightly
    container_name: freeswitch
    hostname: freeswitch
    restart: always
    volumes:
      - ./freeswitch/conf/vanilla:/etc/freeswitch
      - ./logs:/usr/local/freeswitch/log
    network_mode: host
    privileged: true
    ports:
      - "8021:8021/tcp"
      - "5060:5060/tcp"
      - "5060:5060/udp"
      - "5080:5080/tcp"
      - "5080:5080/udp"
      - "5061:5061/tcp"
      - "5061:5061/udp"
      - "5081:5081/tcp"
      - "5081:5081/udp"
      - "7443:7443/tcp"
      - "5070:5070/udp"
      - "5070:5070/tcp"
      - "64535-65535:64535-65535/udp"
      - "16384-32768:16384-32768/udp"
