services:
  freeswitch:
    image: ghcr.io/mohan-cao/freeswitch-docker-image:v1.0.0
    container_name: freeswitch
    hostname: freeswitch
    restart: always
    volumes:
      - ./freeswitch/conf/vanilla:/etc/freeswitch
    network_mode: host
    privileged: true
